//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Ticari_Otomasyon_Proje.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class TBLCARI
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public TBLCARI()
        {
            this.TBLCARIHAREKET = new HashSet<TBLCARIHAREKET>();
        }
    
        public int CARIID { get; set; }
        public string AD { get; set; }
        public string SOYAD { get; set; }
        public string IL { get; set; }
        public string ILCE { get; set; }
        public string TELEFON { get; set; }
        public string MAIL { get; set; }
        public string TC { get; set; }
        public string ADRES { get; set; }
        public string VERGIDAIRESI { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TBLCARIHAREKET> TBLCARIHAREKET { get; set; }
    }
}
