//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Ticari_Otomasyon_Proje.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class TBLURUN
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public TBLURUN()
        {
            this.TBLCARIHAREKET = new HashSet<TBLCARIHAREKET>();
        }
    
        public int URUNID { get; set; }
        public string URUNAD { get; set; }
        public Nullable<decimal> ALISFIYAT { get; set; }
        public Nullable<decimal> SATISFIYAT { get; set; }
        public Nullable<short> STOK { get; set; }
        public Nullable<bool> KRITIKSEVIYE { get; set; }
        public Nullable<int> KATEGORI { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TBLCARIHAREKET> TBLCARIHAREKET { get; set; }
        public virtual TBLKATEGORI TBLKATEGORI { get; set; }
    }
}
